/**
 * Interactive text meetings for "SiteCommand Training" sandboxes.
 *
 * A scheduled task can carry a meeting: the Day panel hyperlinks the task text,
 * and clicking it opens /training/meeting?project=…&meeting=… in a new tab. The
 * meeting is a text conversation — the fake attendees (GC precon team personas)
 * talk in turn, and whenever it's the PM's (the trainee's) turn to weigh in, the
 * page prompts them to respond via text. The attendees' turns are generated by
 * Gemini (see app/api/projects/[id]/training/meetings/[meetingId]), grounded in
 * the agenda and facts defined here. The meeting sticks to the agenda; if the
 * trainee asks something off-script, the attendees answer the aside in character
 * and then steer back to the current agenda item.
 *
 * This module is pure, client-safe content (types + the meeting definitions +
 * lookup helpers) so both the Day panel and the API route can import it. Only
 * the Day-1 PM bid-review meeting is defined today; add future meetings to
 * TRAINING_MEETINGS.
 */

import type { SimRole } from "@/lib/simulation-constants";
import type { SkillKey } from "@/lib/training-skills";
import { TRAINING_SUBS } from "@/lib/training-emails";
import { HC_MEETINGS, HEALTHCARE_TYPE } from "@/lib/training-healthcare";

export type MeetingSpeaker = {
  /** Stable key used in transcripts ("okafor"). "user" is reserved for the PM. */
  key: string;
  name: string;
  title: string;
  /** How this persona talks — grounding for the LLM, not shown in the UI. */
  style: string;
};

export type MeetingAgendaItem = {
  title: string;
  /** Grounding facts / talking points the attendees work from on this item. */
  points: string[];
};

export type MeetingTurn = {
  /** A speaker key from the meeting's speakers, or "user" for the PM. */
  speaker: string;
  text: string;
};

/**
 * A hidden "test" planted in the meeting. The attendees surface the clue
 * naturally (per `plant`) but never resolve it themselves — the checkpoint is
 * whether the PM catches it (flags it, asks about it, turns it into a
 * decision/action). Scored when the meeting adjourns; results land in the
 * saved minutes and the phase Job Review.
 */
export type MeetingCheckpoint = {
  id: string;
  /** Short label shown in the score card. */
  title: string;
  /** What catching it looks like — shown in the minutes and used for scoring. */
  expectation: string;
  /**
   * LLM-only instruction for how the attendees drop the clue in conversation
   * (never shown to the trainee, never dumped into fallback dialogue).
   */
  plant: string;
  /** Agenda item (0-based) where the clue belongs. */
  plantAgendaIndex: number;
  /**
   * Natural sentence appended to the canned fallback turn for that agenda item
   * so the clue still surfaces when Gemini is unavailable. Omit when the clue
   * is already carried by the agenda points / bid tab.
   */
  fallbackLine?: string;
  /**
   * Degraded scoring heuristic when Gemini is unavailable: the checkpoint
   * counts as caught if any PM turn contains any of these (case-insensitive).
   */
  keywords: string[];
};

/**
 * A timed question posed during a meeting's site walk. The trainee has
 * `timeLimitSeconds` (meeting-level) to answer on the spot:
 *   - FULL credit — a confident, substantively correct answer.
 *   - HALF credit — they don't have the fact but correctly tell the asker
 *     where the information lives (spec section, submittal log, fixture
 *     schedule, testing reports, …).
 *   - NO credit — the timer expires, or the answer is vague/wrong.
 * Asked deterministically by the client (no LLM between questions) so the
 * countdown is reliable; graded server-side when the minutes are generated.
 */
export type WalkQuestion = {
  id: string;
  /** Speaker key of the persona asking (must be one of the meeting speakers). */
  speakerKey: string;
  /** Short label shown in the score card. */
  title: string;
  /** The full turn text — scene-setting + the question itself. */
  ask: string;
  /** What a full-credit answer contains (drives the judge and the score card). */
  fullAnswer: string;
  /** Where the info lives — correctly naming this earns half credit. */
  sourceHint: string;
  /** Skill this question evidences in the competency profile. */
  skill: SkillKey;
  /** Degraded grading: any of these in the answer → full credit. */
  fullKeywords: string[];
  /** Degraded grading: any of these in the answer → half credit. */
  sourceKeywords: string[];
};

export type MeetingWalk = {
  /** Deterministic transition turn that starts the walk after the sit-down agenda. */
  intro: MeetingTurn;
  /** Seconds the trainee has to answer each question (the "on the spot" window). */
  timeLimitSeconds: number;
  questions: WalkQuestion[];
  /** Deterministic closing turn after the last question — then the meeting adjourns. */
  outro: MeetingTurn;
};

export type TrainingMeeting = {
  id: string;
  role: SimRole;
  /** In-sim day the meeting's task lands on. */
  day: number;
  /** Exact TrainingTask.task string this meeting hyperlinks in the Day panel. */
  taskMatch: string;
  title: string;
  objective: string;
  deliverable: string;
  /** Attendees other than the PM. The first entry runs the meeting. */
  speakers: MeetingSpeaker[];
  agenda: MeetingAgendaItem[];
  /** Hidden tests scored against the transcript when the meeting adjourns. */
  checkpoints: MeetingCheckpoint[];
  /**
   * Deterministic opening turns (served without an LLM call) that run the
   * meeting up to the first point where the PM is expected to respond.
   */
  opening: MeetingTurn[];
  /**
   * Reference facts the attendees (and the minute-taker/scorer) work from —
   * e.g. the bid tab, or the project status snapshot for an OAC. Plain text.
   */
  facts?: string;
  /** Optional timed site-walk Q&A that runs after the sit-down agenda. */
  walk?: MeetingWalk;
};

// ---------------------------------------------------------------------------
// Day 1 — Bid review & vendor short-list (Project Manager)
// ---------------------------------------------------------------------------

/** Roster sub's seeded bid for a trade (keeps meeting numbers consistent with
 *  the buyout email threads). */
function rosterBid(trade: string): number {
  return TRAINING_SUBS.find((s) => s.trade === trade)?.bid ?? 0;
}

function money(value: number): string {
  return `$${Math.round(value).toLocaleString("en-US")}`;
}

/**
 * The bid tab the precon team walks through. One entry per trade: the estimate
 * line, each bidder (the seeded roster firm is flagged), and any flags the team
 * should raise. Competitor firms are fictional; the roster firm's number comes
 * from TRAINING_SUBS so the meeting agrees with the seeded buyout emails.
 */
type BidLine = { firm: string; amount: number | null; roster?: boolean; note?: string };
type BidTabTrade = { trade: string; estimate: number; bids: BidLine[]; flag?: string };

const BID_TAB: BidTabTrade[] = [
  {
    trade: "Concrete / Foundations",
    estimate: 4_400_000,
    bids: [
      { firm: "Bedrock Concrete", amount: rosterBid("Concrete / Foundations"), roster: true, note: "Clean scope, acknowledged Addenda 1–2" },
      { firm: "Apex Concrete Group", amount: 4_470_000 },
      { firm: "Southland Structures", amount: 4_690_000, note: "Excludes pump premiums" },
    ],
  },
  {
    trade: "Structural Steel / Framing",
    estimate: 6_600_000,
    bids: [
      { firm: "Palmetto Steel", amount: 6_540_000, note: "Did NOT acknowledge Addendum 2; excludes metal deck — likely a $400k+ scope gap" },
      { firm: "Ironclad Steel Erectors", amount: rosterBid("Structural Steel / Framing"), roster: true, note: "Full scope incl. deck; best erection schedule" },
      { firm: "TriState Erectors", amount: 7_150_000 },
    ],
    flag: "Apparent low (Palmetto) is not truly low once the deck gap and Addendum 2 are plugged.",
  },
  {
    trade: "Electrical",
    estimate: 5_500_000,
    bids: [
      { firm: "Voltura Electric", amount: rosterBid("Electrical"), roster: true, note: "Carries switchgear at ~42-week lead per distributor quote" },
      { firm: "Gridline Electrical", amount: 5_620_000 },
    ],
    flag: "Only two responsive bids — thin coverage; switchgear release is schedule-critical.",
  },
  {
    trade: "Plumbing",
    estimate: 3_250_000,
    bids: [
      { firm: "Cardinal Plumbing", amount: rosterBid("Plumbing"), roster: true },
      { firm: "BlueRiver Mechanical", amount: 3_180_000, note: "Close second — good leverage for the scope call" },
      { firm: "Pinnacle Plumbing", amount: 3_540_000 },
    ],
  },
  {
    trade: "HVAC / Mechanical",
    estimate: 5_000_000,
    bids: [
      { firm: "Northwind Mechanical", amount: rosterBid("HVAC / Mechanical"), roster: true, note: "Flagged long RTU lead times" },
      { firm: "Meridian Air Systems", amount: 5_060_000 },
      { firm: "Delta Comfort", amount: 5_390_000, note: "Excludes controls / BMS" },
    ],
  },
  {
    trade: "Fire Protection",
    estimate: 1_700_000,
    bids: [
      { firm: "Sentinel Fire Systems", amount: rosterBid("Fire Protection"), roster: true },
      { firm: "Guardian Sprinkler", amount: 1_720_000 },
    ],
  },
  {
    trade: "Roofing",
    estimate: 2_350_000,
    bids: [
      { firm: "Summit Ridge Roofing", amount: rosterBid("Roofing"), roster: true, note: "Manufacturer price-increase notice — number holds 45 days" },
      { firm: "Crestline Roofing", amount: 2_410_000 },
    ],
    flag: "Price hold expires in 45 days — award or lock pricing before then.",
  },
  {
    trade: "Glazing / Curtain Wall",
    estimate: 3_600_000,
    bids: [
      { firm: "MetroGlass", amount: 3_480_000, note: "Excludes engineering calcs and field mock-up; slow submittals on our last job with them" },
      { firm: "ClearSpan Glazing", amount: rosterBid("Glazing / Curtain Wall"), roster: true, note: "Full scope incl. engineering and mock-up" },
      { firm: "VistaPane", amount: 3_930_000 },
    ],
    flag: "Apparent low (MetroGlass) carries real scope gaps and performance risk.",
  },
];

/** Render the bid tab as plain text for the LLM's grounding context. */
export function bidTabText(): string {
  return BID_TAB.map((t) => {
    const lines = t.bids
      .map((b) => {
        const parts = [
          `  - ${b.firm}: ${b.amount === null ? "no bid" : money(b.amount)}`,
          b.roster ? "(the firm the team knows and has bid history with)" : "",
          b.note ? `— ${b.note}` : "",
        ].filter(Boolean);
        return parts.join(" ");
      })
      .join("\n");
    return `${t.trade} (estimate ${money(t.estimate)}):\n${lines}${t.flag ? `\n  FLAG: ${t.flag}` : ""}`;
  }).join("\n\n");
}

const BID_REVIEW_MEETING: TrainingMeeting = {
  facts: bidTabText(),
  id: "pm-day1-bid-review",
  role: "project_manager",
  day: 1,
  taskMatch:
    "Meet with preconstruction team to review bid results and develop short-list of vendors by trade",
  title: "Bid Review & Vendor Short-List",
  objective:
    "Walk the bid results trade by trade with the preconstruction team and agree on a short-list of vendors for each major trade.",
  deliverable: "Bid tab / vendor short-list",
  speakers: [
    {
      key: "okafor",
      name: "David Okafor",
      title: "Preconstruction Manager",
      style:
        "Runs the meeting. Organized and steady; keeps things moving through the agenda, summarizes decisions, and hands questions to the right person. Politely steers off-topic discussion back to the agenda.",
    },
    {
      key: "nguyen",
      name: "Rachel Nguyen",
      title: "Estimator",
      style:
        "Owns the numbers. Precise and quick with figures — quotes bid amounts, spreads vs. estimate, exclusions, and scope gaps from the bid tab. Flags anything that smells like a buyout bust.",
    },
    {
      key: "bennett",
      name: "Marcus Bennett",
      title: "Project Executive",
      style:
        "Big-picture and commercial. Cares about protecting budget and schedule, sub relationships, and risk. Speaks less often but weighs in on award strategy and pushes for decisions.",
    },
  ],
  agenda: [
    {
      title: "Bid coverage & overall results",
      points: [
        "All eight major trades received bids; coverage is decent overall.",
        "Two coverage concerns: Electrical drew only two responsive bids, and two trades have apparent-low bids with real scope gaps (Steel and Glazing).",
        "In aggregate the bids are close to estimate — roughly on budget if scope gaps are managed in the scope-review calls.",
      ],
    },
    {
      title: "Structural & envelope trades (concrete, steel, roofing, glazing)",
      points: [
        "Concrete: Bedrock is low with a clean scope — straightforward recommendation.",
        "Steel: Palmetto is apparent low but missed Addendum 2 and excludes metal deck (~$400k+ gap); Ironclad is full-scope with the best erection schedule.",
        "Roofing: Summit Ridge is low but their manufacturer price hold expires in 45 days — needs an early award or locked pricing.",
        "Glazing: MetroGlass is apparent low but excludes engineering and the field mock-up, and was slow on submittals last job; ClearSpan is full-scope.",
      ],
    },
    {
      title: "MEP trades (electrical, plumbing, HVAC, fire protection)",
      points: [
        "Electrical: Voltura is low with only two bids; their number carries switchgear at ~42-week lead — release timing is schedule-critical.",
        "Plumbing: Cardinal is low with BlueRiver a close second — good leverage going into scope calls.",
        "HVAC: Northwind is low and flagged long RTU lead times; Delta Comfort excludes controls/BMS.",
        "Fire protection: Sentinel is low with a clean number.",
      ],
    },
    {
      title: "Short-list decisions by trade",
      points: [
        "Go trade by trade and have the PM confirm the short-list (typically the top one or two firms per trade to take into scope-review calls).",
        "Team recommendation: Bedrock (concrete), Ironclad over Palmetto (steel — gap risk), Voltura (electrical), Cardinal + BlueRiver (plumbing), Northwind (HVAC), Sentinel (fire), Summit Ridge (roofing — mind the price hold), ClearSpan over MetroGlass (glazing — scope/performance risk).",
        "The PM owns the final call; the team pushes back respectfully if a pick carries risk they've flagged.",
      ],
    },
    {
      title: "Action items & award targets",
      points: [
        "PM to schedule scope-review calls with short-listed firms for the major trades next week.",
        "Prioritize long-lead: switchgear (electrical) and RTUs (HVAC) need early release / LOIs to protect the schedule.",
        "Roofing pricing must be locked before the 45-day hold expires.",
        "Target: awards out by end of next week; the documented bid tab / short-list is the deliverable from this meeting.",
      ],
    },
  ],
  checkpoints: [
    {
      id: "slab-milestone",
      title: "30-day slab-pour milestone",
      expectation:
        "Catches the owner-agreement milestone (first slab-on-grade poured within 30 days of contract start) and connects it to expediting the concrete award — awarding Bedrock immediately and getting mobilization moving.",
      plant:
        "While the concrete trade is being discussed, have Marcus Bennett mention IN PASSING that the owner agreement carries a milestone with liquidated damages: the first slab-on-grade must be poured within 30 days of contract start (NTP). Drop it as a side remark and move on — do NOT spell out what it means for buyout sequencing and do NOT propose the fix yourselves. If the PM never picks it up, let it go unresolved.",
      plantAgendaIndex: 1,
      fallbackLine:
        "Marcus also flagged something buried in the owner agreement — a milestone with liquidated damages requiring the first slab pour within 30 days of contract start.",
      keywords: ["slab", "30 day", "30-day", "thirty day", "liquidated", "milestone"],
    },
    {
      id: "steel-scope-gap",
      title: "Steel apparent-low scope gap",
      expectation:
        "Doesn't take Palmetto's apparent-low steel bid at face value — picks Ironclad, or requires the metal-deck / Addendum 2 gap plugged before any award to Palmetto.",
      plant:
        "The bid tab already carries this: Palmetto Steel is apparent low but missed Addendum 2 and excludes metal deck. Present the numbers factually and let the PM make the call — don't make the decision for them.",
      plantAgendaIndex: 1,
      keywords: ["ironclad", "palmetto", "deck", "addendum"],
    },
    {
      id: "roofing-price-hold",
      title: "Roofing 45-day price hold",
      expectation:
        "Acts on the roofing price hold — commits to awarding Summit Ridge or locking their pricing before the 45-day manufacturer hold expires.",
      plant:
        "The bid tab already carries the 45-day manufacturer price hold on Summit Ridge's number. State it as a fact; let the PM decide the urgency.",
      plantAgendaIndex: 1,
      keywords: ["price hold", "45-day", "45 day", "lock roofing", "lock pricing", "lock the roofing"],
    },
    {
      id: "switchgear-lead",
      title: "Switchgear long-lead release",
      expectation:
        "Flags the ~42-week switchgear lead time and calls for an early electrical award, LOI, or early switchgear release to protect the schedule.",
      plant:
        "The bid tab already carries Voltura's ~42-week switchgear lead. Mention it with the electrical numbers; don't propose the early release yourselves.",
      plantAgendaIndex: 2,
      keywords: ["switchgear", "loi", "early release", "long lead", "long-lead"],
    },
    {
      id: "glazing-risk",
      title: "Glazing apparent-low risk",
      expectation:
        "Avoids MetroGlass's scope-gapped low bid — short-lists ClearSpan, or requires engineering and the field mock-up included before considering MetroGlass.",
      plant:
        "The bid tab already carries MetroGlass's exclusions (engineering calcs, field mock-up) and their submittal history. Present it factually and let the PM decide.",
      plantAgendaIndex: 1,
      keywords: ["clearspan", "metroglass", "mock-up", "mockup"],
    },
  ],
  opening: [
    {
      speaker: "okafor",
      text: "Thanks for making time on day one — this is the most important hour of your week. Purpose of this meeting is simple: walk the bid results trade by trade and leave with a short-list of vendors for each major trade so you can start scope calls. Agenda is: coverage and overall results, structural and envelope trades, MEP trades, short-list decisions, then action items and award targets. Rachel, want to start us off with coverage?",
    },
    {
      speaker: "nguyen",
      text: "Sure. We got bids on all eight major trades, so coverage is decent overall. Two things to keep in mind as we go: Electrical only drew two responsive bids, and on Steel and Glazing the apparent low bidders both have real scope gaps — so \"low\" isn't low once you plug the holes. In aggregate we're sitting right around the estimate, which is a good place to start buyout from.",
    },
    {
      speaker: "bennett",
      text: "And from my side — the goal today is to protect the budget and the schedule. A cheap number with a scope gap is how buyout busts happen, so let's short-list firms we can actually build with.",
    },
    {
      speaker: "okafor",
      text: "Agreed. Before we dig into the trades — any questions on how the bids came in, or any trade you want us to spend extra time on?",
    },
  ],
};

// ---------------------------------------------------------------------------
// Recurring OAC meetings + site walks (Project Manager) — every 30 in-sim days
// ---------------------------------------------------------------------------

/** Shared attendees for the OAC meetings: the owner's rep and the architect
 *  (both match their inbox-feed personas in lib/training-inbox.ts). */
const OAC_SPEAKERS: MeetingSpeaker[] = [
  {
    key: "whitfield",
    name: "Elaine Whitfield",
    title: "Director of Development (Owner)",
    style:
      "Runs the OAC as the owner's representative. Commercially sharp and direct; cares about schedule certainty, cost exposure, and not being surprised in front of her investment committee. Asks pointed questions and expects crisp, confident answers — polite but visibly unimpressed by vagueness.",
  },
  {
    key: "chen",
    name: "Laura Chen",
    title: "Project Architect, Halford Studio Architects",
    style:
      "Detail-oriented on design intent, specifications, finishes, and the submittal record. Collegial but precise — asks about specific materials, fixtures, and coordination items, and quietly notes when the answer should be coming out of a document the PM ought to know.",
  },
];

const OAC_WALK_TIME_LIMIT = 30;

const OAC_MEETING_DAY30: TrainingMeeting = {
  facts: `PROJECT STATUS SNAPSHOT (Month 1 OAC):
- Foundations and slab-on-grade complete; vertical structure/framing underway.
- Long-lead items in play: main switchgear (~42-week factory lead from approved submittals), HVAC RTUs (delivery risk flagged by vendor), elevator package (fab slot tied to submittal approval).
- The owner asked for ROM pricing on adding EV charging stations and expects it tracked as a potential change.
- Recent field items: sanitary trench compaction failures in Area B (retest status matters), low 7-day concrete breaks flagged by the testing lab (28-day results pending).
- The architect is watching the elevator submittal package and interior finish submittals.
- Substantial completion date unchanged so far; the owner reports to her investment committee monthly and hates surprises.`,
  id: "pm-day30-oac",
  role: "project_manager",
  day: 30,
  taskMatch:
    "Run the monthly OAC meeting and walk the site with the owner and architect",
  title: "Monthly OAC Meeting & Site Walk — Month 1",
  objective:
    "Give the owner and architect a straight status picture — schedule, cost, and open items — then walk the site and answer their questions on the spot.",
  deliverable: "OAC minutes + action items",
  speakers: OAC_SPEAKERS,
  agenda: [
    {
      title: "Schedule & milestone status",
      points: [
        "Foundations and slab-on-grade are complete; vertical structure is underway — the owner wants to hear whether the sequence and the substantial-completion date still hold.",
        "Elaine reports to her investment committee monthly and needs the PM's schedule statement on record, including the top schedule risk in the PM's own words.",
        "Long-lead procurement status matters here: switchgear, RTUs, and the elevator package are the items ownership has heard about before.",
      ],
    },
    {
      title: "Budget, change orders & potential changes",
      points: [
        "Elaine wants the change order log walked: what's approved, what's pending, and what's potential — including the EV-charging scope she asked to be tracked as a potential change.",
        "Laura notes any design clarifications in flight that could carry cost (RFI-driven changes).",
        "The owner's standing rule: no surprises — anything that might become a number should be on the potential-change log today.",
      ],
    },
    {
      title: "Open items & 30-day look-ahead",
      points: [
        "Submittal cycle status: elevator package and interior finish submittals are the ones the architect is watching.",
        "Testing/inspection status on the structure and site utilities.",
        "Once open items are covered, the group heads out for the site walk — hard hats on; the walk is part of this meeting.",
      ],
    },
  ],
  checkpoints: [
    {
      id: "oac30-ev-change-log",
      title: "EV scope on the potential-change log",
      expectation:
        "When cost and changes come up, proactively accounts for the owner's EV-charging request — confirms it's tracked as a potential change with ROM/pricing status, without Elaine having to drag it out.",
      plant:
        "During the cost/change-order agenda item, have Elaine ask generally about the potential-change log without naming EV charging herself at first. Whether the PM surfaces the EV scope unprompted is the test — if they don't, she eventually asks pointedly and is visibly unimpressed.",
      plantAgendaIndex: 1,
      keywords: ["ev", "charging", "potential change", "rom", "change event"],
    },
  ],
  opening: [
    {
      speaker: "whitfield",
      text: "Good morning — thanks for hosting. Standing agenda, same as every month: schedule and milestones, then cost and change orders, then open items and the thirty-day look-ahead. After that I'd like to walk the site; Laura and I both have things we want to see. Let's start with schedule — give me the status picture, and I want to hear your top risk in your own words.",
    },
    {
      speaker: "chen",
      text: "Morning. From my side I'll want to touch the submittal log when we get to open items — a couple of packages are on my desk and a couple should be on yours. But schedule first.",
    },
  ],
  walk: {
    intro: {
      speaker: "whitfield",
      text: "(Standing) Alright — hard hats. Let's walk. Fair warning: as we go, Laura and I are going to ask you questions about what we're looking at. You're the PM — we expect you to have the answers on the spot. If you don't have one memorized, tell us exactly where you'd find it and when we'll have it; that's an acceptable second-best. Vague doesn't work for me.",
    },
    timeLimitSeconds: OAC_WALK_TIME_LIMIT,
    questions: [
      {
        id: "d30-switchgear-delivery",
        speakerKey: "whitfield",
        title: "Switchgear delivery date",
        ask: "(Stopping at the main electrical room — bare CMU walls, conduit stubs in the slab) Here's the room everyone keeps talking about. When does the switchgear actually land on site, and what's the plan if it slips?",
        fullAnswer:
          "States the expected delivery window tied to the release/approved submittals (the ~42-week factory lead), and gives a contingency — temporary power sequencing, energization gate coordination with the utility — if it slips.",
        sourceHint:
          "The procurement log / the switchgear vendor's quote and order confirmation (Gulf States Switchgear thread) — offer to confirm the current factory date after the walk.",
        skill: "schedule",
        fullKeywords: ["42", "week", "lead", "delivery", "temp power", "temporary power", "energization"],
        sourceKeywords: ["procurement log", "vendor", "quote", "confirm", "order confirmation", "follow up", "after the walk"],
      },
      {
        id: "d30-lobby-fixtures",
        speakerKey: "chen",
        title: "Lobby light fixtures",
        ask: "(In the future lobby, looking up at the double-height ceiling) Quick one while we're standing here — what light fixtures go in this lobby? The decorative package, not the cans.",
        fullAnswer:
          "Names the decorative fixture package confidently — the specified pendant/fixture type from the lighting fixture schedule — and its submittal status (approved / in review / pending resubmittal).",
        sourceHint:
          "The lighting fixture schedule on the electrical sheets (E-series) and the lighting submittal in the submittal log — offer to pull the exact fixture type from there.",
        skill: "submittals",
        fullKeywords: ["pendant", "fixture schedule", "approved", "submittal", "specified"],
        sourceKeywords: ["fixture schedule", "e-series", "electrical sheets", "submittal log", "spec", "pull", "look"],
      },
      {
        id: "d30-schedule-threat",
        speakerKey: "whitfield",
        title: "Biggest schedule threat",
        ask: "(Walking the structure line) My board asks me the same question every month, so now I'm asking you: are we still making substantial completion, and what is the single biggest threat to that date right now?",
        fullAnswer:
          "Gives a direct yes/no-with-context on the date and names one specific, current threat (e.g. long-lead equipment, envelope dry-in pace, elevator submittal cycle) with what's being done about it.",
        sourceHint:
          "The master schedule / monthly report — commit to sending the updated schedule narrative and critical-path view after the meeting.",
        skill: "comms",
        fullKeywords: ["on schedule", "on track", "substantial completion", "critical path", "risk", "threat", "mitigation"],
        sourceKeywords: ["schedule update", "monthly report", "send you", "critical path", "after the meeting"],
      },
      {
        id: "d30-concrete-breaks",
        speakerKey: "chen",
        title: "Concrete strength results",
        ask: "(At a column line on level 2, hand on the concrete) These columns — did the 28-day cylinder breaks come back, and were there any low breaks anywhere in the structure I should know about?",
        fullAnswer:
          "Knows the testing status — including the flagged low 7-day breaks and the plan (hold for 28-day results, cores/investigation if they don't recover) — and where results stand today.",
        sourceHint:
          "The testing agency's reports in the transmittals (Meridian Testing Labs) — offer to forward the latest break reports today.",
        skill: "field",
        fullKeywords: ["28-day", "28 day", "breaks", "low break", "cylinder", "cores", "psi"],
        sourceKeywords: ["testing", "lab", "reports", "transmittal", "forward", "meridian"],
      },
    ],
    outro: {
      speaker: "whitfield",
      text: "(Back at the trailer, hard hat off) Good walk. Laura and I will get you our punch of observations by end of week — get us the minutes with action items and owners by tomorrow. Same time next month. Meeting adjourned.",
    },
  },
};

const OAC_MEETING_DAY60: TrainingMeeting = {
  facts: `PROJECT STATUS SNAPSHOT (Month 2 OAC):
- Interior finishes underway floor by floor; envelope dried in; MEP trim and controls point-to-point in progress.
- Occupancy-critical chain: fire alarm acceptance test (fire marshal requires ERRC verification), elevator state inspection (inspector backlog running long), then certificate of occupancy.
- Billing posture: accounting flagged the mechanical sub's ductwork billed ~80% vs ~55% installed — the pay app needed a pencil-draw cut to earned value.
- The owner has requested early access for her FF&E vendor (lobby) and previously asked about running HVAC early for temporary conditioning.
- The architect returned the elevator submittal split (part approved, part revise-and-resubmit) and is watching finish resubmittals and mock-up sign-offs.
- Retainage/closeout billing prep is starting; the potential-change log needs to be converted or closed.`,
  id: "pm-day60-oac",
  role: "project_manager",
  day: 60,
  taskMatch:
    "Run the monthly OAC meeting and walk the site with the owner and architect",
  title: "Monthly OAC Meeting & Site Walk — Month 2",
  objective:
    "Status the owner and architect through the finishes push — schedule to substantial completion, billing posture, closeout look-ahead — then answer their questions on the walk.",
  deliverable: "OAC minutes + action items",
  speakers: OAC_SPEAKERS,
  agenda: [
    {
      title: "Schedule to substantial completion",
      points: [
        "Interior finishes are running; the conversation is now about the runway to substantial completion — inspections, commissioning, and the elevator are the gating items.",
        "Elaine is fielding board questions about the delivery date weekly and wants the PM's plain-language commitment plus the float that's left.",
        "Laura wants the finishes sequence and any resubmittals that could stall a floor.",
      ],
    },
    {
      title: "Billing, cost & change order posture",
      points: [
        "Pay application accuracy matters to the owner now — billed-vs-installed on the big trades, retainage posture, and what the final change order log looks like.",
        "Elaine wants to close out the potential-change log: anything not converted to a real number soon dies or becomes a claim fight later.",
      ],
    },
    {
      title: "Closeout & occupancy look-ahead",
      points: [
        "The occupancy-critical chain: fire alarm acceptance testing, the elevator state inspection, life-safety systems, then certificate of occupancy.",
        "Elaine's early-access/FF&E request needs a real answer with conditions, not a shrug.",
        "Once the look-ahead is covered, the group heads out for the site walk — hard hats on; the walk is part of this meeting.",
      ],
    },
  ],
  checkpoints: [
    {
      id: "oac60-billing-integrity",
      title: "Billed-vs-installed honesty",
      expectation:
        "When billing comes up, speaks to pay-application accuracy on the big trades — including that front-loaded billing (the mechanical ductwork pencil draw) gets cut to installed reality rather than certified as billed.",
      plant:
        "During the billing agenda item, have Elaine say she's heard from her lender's inspector that some trades 'look generously billed' — without naming the trade. Whether the PM owns the billed-vs-installed discipline (and the mechanical cut specifically) is the test; don't resolve it for them.",
      plantAgendaIndex: 1,
      fallbackLine:
        "Elaine also mentioned her lender's site inspector felt some trades looked generously billed relative to installed work, and asked how pay applications are being verified.",
      keywords: ["pencil", "installed", "overbill", "cut", "billed", "earned"],
    },
  ],
  opening: [
    {
      speaker: "whitfield",
      text: "Morning. We're inside the last stretch, so today I care about three things: the runway to substantial completion, whether your billing matches reality on the ground, and the closeout chain — inspections, elevator, occupancy. Then we walk; the building finally looks like a building and I want to see the finishes with my own eyes. Start with schedule: where are we, honestly?",
    },
    {
      speaker: "chen",
      text: "Good morning. I'll add — I'm watching the finish floors closely now. When we get to open items I want to talk resubmittals and mock-up sign-offs, because a stalled package at this stage costs a floor a week. But go ahead — schedule.",
    },
  ],
  walk: {
    intro: {
      speaker: "whitfield",
      text: "(Standing) Hard hats — let's go see it. Same rules as last time: we'll ask questions as we walk, and you're on the clock. Know it cold, or tell us exactly where it lives and when we'll have it. Ready?",
    },
    timeLimitSeconds: OAC_WALK_TIME_LIMIT,
    questions: [
      {
        id: "d60-ffe-access",
        speakerKey: "whitfield",
        title: "FF&E early-access conditions",
        ask: "(In the lobby, finishes going in around you) My FF&E vendor keeps calling me for a date to load in this lobby. What has to be true before I can give them one — and when do you think that is?",
        fullAnswer:
          "Lays out the real conditions for early access/beneficial use — finishes and life-safety status in the area, insurance/liability terms, a written early-access agreement, protection plan — and ties them to a realistic window.",
        sourceHint:
          "The early-access request thread with the owner and the prime contract's beneficial-use/occupancy provisions — offer to send the conditions letter this week.",
        skill: "comms",
        fullKeywords: ["early access", "beneficial", "insurance", "agreement", "life safety", "protection", "conditions"],
        sourceKeywords: ["contract", "send you", "letter", "put it in writing", "this week", "provisions"],
      },
      {
        id: "d60-corridor-paint",
        speakerKey: "chen",
        title: "Corridor paint spec",
        ask: "(Running a hand along a freshly painted corridor wall) While we're here — what's the specified corridor paint? Finish and color, per the documents.",
        fullAnswer:
          "Names the specified finish level and color confidently per the finish schedule / painting spec, plus submittal status (approved color draw-downs).",
        sourceHint:
          "The finish schedule on the A-series sheets and painting spec section 09 91 23 / the approved paint submittal — offer to pull the exact finish and color from there.",
        skill: "submittals",
        fullKeywords: ["eggshell", "satin", "finish schedule", "approved", "color", "sw ", "sherwin", "benjamin"],
        sourceKeywords: ["finish schedule", "09 91", "spec section", "submittal", "a-series", "pull", "check the"],
      },
      {
        id: "d60-elevator-inspection",
        speakerKey: "whitfield",
        title: "Elevator inspection & CO buffer",
        ask: "(At the elevator bank, cabs still protected) Walk me through this elevator: when is the state inspection, and how much buffer is between passing it and your certificate-of-occupancy date?",
        fullAnswer:
          "Knows the sequence (install complete → pre-test with the vendor → state inspection) and the current inspector backlog risk, states the scheduled/target window, and quantifies the buffer to CO.",
        sourceHint:
          "The elevator vendor's thread (Apex) and the inspection scheduling with the state — offer to confirm the inspection slot and buffer after the walk.",
        skill: "schedule",
        fullKeywords: ["inspection", "backlog", "buffer", "pre-test", "state", "certificate of occupancy", "co "],
        sourceKeywords: ["confirm", "vendor", "apex", "schedule", "after the walk", "follow up"],
      },
      {
        id: "d60-ceiling-conflict",
        speakerKey: "chen",
        title: "Ceiling grid vs. RCP conflict",
        ask: "(Looking up at the ceiling grid on level 3) Hold on — this grid run at the corridor transition doesn't match my reflected ceiling plan. How are you handling that?",
        fullAnswer:
          "Owns it as a coordination item with a process answer: stop the affected run, verify against the RCP, and get it resolved through an RFI/field clarification with the architect before more grid goes in — not paint over it.",
        sourceHint:
          "The RCP (A-series reflected ceiling plans) and the RFI log — commit to issuing the RFI/field verification today.",
        skill: "field",
        fullKeywords: ["rfi", "hold", "stop", "verify", "coordinate", "field clarification", "rcp"],
        sourceKeywords: ["rfi log", "reflected ceiling", "issue an rfi", "today", "check the drawings"],
      },
    ],
    outro: {
      speaker: "whitfield",
      text: "(Back at the trailer) That's what I needed. Minutes and action items by tomorrow, and Laura will send her observation list. One more of these before we're talking punch walks instead. Adjourned.",
    },
  },
};

/** All defined default-pack meetings. Add future meetings here. */
export const TRAINING_MEETINGS: TrainingMeeting[] = [
  BID_REVIEW_MEETING,
  OAC_MEETING_DAY30,
  OAC_MEETING_DAY60,
];

/** The meeting set for a project type (healthcare uses the VA cast). */
export function meetingsForType(projectType: string | null | undefined): TrainingMeeting[] {
  return projectType === HEALTHCARE_TYPE ? HC_MEETINGS : TRAINING_MEETINGS;
}

/**
 * Look up a meeting by id across BOTH packs. Meeting ids are unique across
 * packs, so the review / minutes / meeting pages (which only know the id) always
 * resolve the right meeting regardless of project type.
 */
export function getTrainingMeeting(id: string): TrainingMeeting | null {
  return (
    TRAINING_MEETINGS.find((m) => m.id === id) ??
    HC_MEETINGS.find((m) => m.id === id) ??
    null
  );
}

/**
 * The meeting hyperlinked by a scheduled task, if any. The default and
 * healthcare packs share task strings + days, so the project type selects which
 * pack's meeting a task links to.
 */
export function meetingForTask(
  role: SimRole,
  day: number,
  task: string,
  projectType?: string | null,
): TrainingMeeting | null {
  return (
    meetingsForType(projectType).find(
      (m) => m.role === role && m.day === day && m.taskMatch === task,
    ) ?? null
  );
}

/** Display lookup for a transcript speaker key. */
export function meetingSpeaker(meeting: TrainingMeeting, key: string): MeetingSpeaker | null {
  return meeting.speakers.find((s) => s.key === key) ?? null;
}
