CREATE TABLE IF NOT EXISTS submittals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  submittal_number INT NOT NULL,
  revision TEXT DEFAULT 'A',
  title TEXT NOT NULL,
  specification_id UUID REFERENCES project_specifications(id) ON DELETE SET NULL,
  submittal_type TEXT,
  status TEXT NOT NULL DEFAULT 'draft',
  responsible_contractor_id UUID REFERENCES directory_contacts(id) ON DELETE SET NULL,
  received_from_id UUID REFERENCES directory_contacts(id) ON DELETE SET NULL,
  submittal_manager_id UUID REFERENCES directory_contacts(id) ON DELETE SET NULL,
  submit_by DATE,
  received_date DATE,
  issue_date DATE,
  final_due_date DATE,
  cost_code TEXT,
  linked_drawings TEXT,
  distribution_list JSONB DEFAULT '[]',
  ball_in_court_id UUID REFERENCES directory_contacts(id) ON DELETE SET NULL,
  lead_time INT,
  required_on_site_date DATE,
  private BOOLEAN DEFAULT FALSE,
  description TEXT,
  attachments JSONB DEFAULT '[]',
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(project_id, submittal_number)
);
