CREATE TABLE IF NOT EXISTS punch_list_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  item_number INT NOT NULL,
  title TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  punch_item_manager_id UUID REFERENCES directory_contacts(id) ON DELETE SET NULL,
  type TEXT,
  assignees JSONB DEFAULT '[]',
  due_date DATE,
  final_approver_id UUID REFERENCES directory_contacts(id) ON DELETE SET NULL,
  distribution_list JSONB DEFAULT '[]',
  location TEXT,
  priority TEXT,
  trade TEXT,
  reference TEXT,
  schedule_impact TEXT,
  cost_impact TEXT,
  cost_codes TEXT,
  private BOOLEAN DEFAULT FALSE,
  description TEXT,
  attachments JSONB DEFAULT '[]',
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(project_id, item_number)
);
